apiVersion: ENC[AES256_GCM,data:BCA=,iv:IIgF9Ni4PNEsjY2fKMBoi+R+prpb0vo4vskE/UEM7xE=,tag:AD52itaYOisVYpHdmDK2RQ==,type:str]
kind: ENC[AES256_GCM,data:xKjD99Ua,iv:yLlAi5Lv1GrP3vKwShXgyZk2YMs8k5XOOA+E3YAU56o=,tag:b2Fc7/zeUk7JYVbCqISpiw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:eQjq1NuMkfXgcrI/np4Wkw==,iv:uetYBC0S/dCTv1dbBqRqK9+yRdFYnsUwpGm660VZY1w=,tag:X0sQri9mNSToZReT0cOZ9A==,type:str]
    namespace: ENC[AES256_GCM,data:r/hgqA==,iv:EqE6rp4U/fcV/5ZxFkrKMBSKIhtpuRpo5weCK+fPk7Q=,tag:cdulT6i/HoqTMcqRLAeLxw==,type:str]
type: ENC[AES256_GCM,data:oDoo80PC,iv:BzOEu/Y+OUXXEsNxaMRKtmnErcNku2ENFw1l8B8ivBo=,tag:cPvF8uZ3+GgHqGwCqolzhg==,type:str]
stringData:
    token: ENC[AES256_GCM,data:DCQb6Kf0Uc+1crA3LKzeZjQkKgbue5FX/CHeIXv8MTz5u2DSy56rCQHj+fKh1RQvcKFs2uLIptsGSO5vS3aYxeLMMGvwwlbdFA4VsLX0F5SkDcMWhRnVcKPzbku+PorX20ZtGDP9kcMSWu6A,iv:k5Pk6eGKgYyvgMbkn28f0p9qo3T1/y8po0ttcYxobtw=,tag:6+8qoM0PdTCNQkqEJUNz2w==,type:str]
sops:
    age:
        - recipient: age17zqyk4za0q6md4tp0grlmlxnhppjvsnfalx987wsl8fgmhfx4fzq3g69m3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ3BESlFMdE1XZmpxbmNq
            RTcyYTNWTi80aFhRZUV1UHBDdzg3U1IydkNzCjlSU1VzNHFHUlNSNmsxMWlRMEY0
            RzMrN1NabVhCMWNrMUxmeHJRVm5XT3cKLS0tIDFGV1BtZVJsOEp0aUd6VUpwaGZl
            RGcrMHFmdHZrSWdBaFB2MlBYRGlOY1kKy/keZ8yVaOo3v7Cq1AgZlvQtI/Dsg59d
            +undI/IobtkFV8YURldyM8qnvxNWzyHwAJL0Pu66jrsgWG95ORybkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T22:52:22Z"
    mac: ENC[AES256_GCM,data:mNaXBkivFEOsggcEmG/dqN9NSJhKx+fGj1X8bcMOgqGTTCLoiKg2Bj+lYNspFVOxG28ZZfdbWB1nCWrZU7ffBtHjnoTwZKOPVkIuPMkMQh9HlFakIiSB6KSGjenLH2DUdz8WUVk77gaqugiM8kBlooVHNpa860+WUj55tR38mMA=,iv:Td+czZZEGBi1AA8cF1l2ePuBvwtxdl/gJeYm2YK3tLA=,tag:VQGXwUjiNVk94pQma6P1Vw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:/HQ=,iv:Ynt/6Pf6eXSrvY9OJeuNFAJdD2Q9bkn3BwkpPd/iXcs=,tag:No//187oNCxfB/a3S0PCsg==,type:str]
kind: ENC[AES256_GCM,data:SbgsVbXV,iv:AFhWqSDHG94l8DRNGm1rCluDPoNYsopBSXVpPehlIoI=,tag:L1bkKDfof7YbdoT1AJsR1w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IFD4u3CUhA3fTVSmR0OKa3A=,iv:no9+FfgO5U4YJkXnKE7uwIhgDIwt/DKXtP9HQ+HRc4A=,tag:ljHyu+pnRnOnOFKPaYXDLg==,type:str]
    namespace: ENC[AES256_GCM,data:2eXeVQ==,iv:+knr/hra3QakHaFL8qAnyPaR/OrLMeQzv1hDFnb/at0=,tag:YBVGFjRf/aqsIT/Y5dQMzw==,type:str]
type: ENC[AES256_GCM,data:ly6Lzurc,iv:nysKi0Q/Fddc73IxATFwGDodzotNVYavxCyGq0mZl5A=,tag:X40OKV3UJzGbNQ2noJMJ7w==,type:str]
stringData:
    token: ENC[AES256_GCM,data:auRyHaQzfIgiacgCzO/1hdkLWWZ3/gv2iK4BRZHCLu7sxSDX/NjSYXm9+PZMqCTycnbSQDMP/Om7bcTFvNIVtiLw8iBlWPWT,iv:zpikIsU4tIITkYestxOxqc1FUcWZ2I5HC3rag6Avqv4=,tag:MA8wOXMTcsfoDdbbZ3z2Vw==,type:str]
sops:
    age:
        - recipient: age17zqyk4za0q6md4tp0grlmlxnhppjvsnfalx987wsl8fgmhfx4fzq3g69m3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ3BESlFMdE1XZmpxbmNq
            RTcyYTNWTi80aFhRZUV1UHBDdzg3U1IydkNzCjlSU1VzNHFHUlNSNmsxMWlRMEY0
            RzMrN1NabVhCMWNrMUxmeHJRVm5XT3cKLS0tIDFGV1BtZVJsOEp0aUd6VUpwaGZl
            RGcrMHFmdHZrSWdBaFB2MlBYRGlOY1kKy/keZ8yVaOo3v7Cq1AgZlvQtI/Dsg59d
            +undI/IobtkFV8YURldyM8qnvxNWzyHwAJL0Pu66jrsgWG95ORybkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T22:52:22Z"
    mac: ENC[AES256_GCM,data:mNaXBkivFEOsggcEmG/dqN9NSJhKx+fGj1X8bcMOgqGTTCLoiKg2Bj+lYNspFVOxG28ZZfdbWB1nCWrZU7ffBtHjnoTwZKOPVkIuPMkMQh9HlFakIiSB6KSGjenLH2DUdz8WUVk77gaqugiM8kBlooVHNpa860+WUj55tR38mMA=,iv:Td+czZZEGBi1AA8cF1l2ePuBvwtxdl/gJeYm2YK3tLA=,tag:VQGXwUjiNVk94pQma6P1Vw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:3MI=,iv:PoiljSuprUAMoMX+SIZMeV7o1EnLJMxp7pwVuPM52hk=,tag:sOmCQDwIlphdVxwgndzMLQ==,type:str]
kind: ENC[AES256_GCM,data:6PRTTKEU,iv:xKWnXmudlhGAEYKzfjH3Ofzu2t5hVOoz9Nf4G2Mr5c8=,tag:NnEsc4n2QCsrKSMWOL1dMQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dFBeUSboqoCqTQdiCQn+,iv:0qx3PE/M0zNsabu0pB1MTRP2fYND4AgdArmQww1VeJQ=,tag:FP4XPhDzAXgt8roUErgcgQ==,type:str]
    namespace: ENC[AES256_GCM,data:gIrAUw==,iv:dJVrgyImtK7r6bQUhg3yJeLPRJbf5GARJP9jIFT/Iwg=,tag:f1XrUAN2XqPsxvHpzsM8TQ==,type:str]
type: ENC[AES256_GCM,data:cBng5Jy6,iv:SOizeHRY3s+oR3CyrQ+wWwDGSjEQI8Ard6/EhLxBiyw=,tag:DA5iMoEdtPVhJJU0Ig6GZg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:kC0cVNppOVcCxNZ93n7KL4luwBiz7mJX+dYJpmgW/Fg=,iv:y3Gwa7Y0uEltHGUj96prV7yXtmzsESWJEGhbv1INFiw=,tag:x83z2Z/Cam7L9+pCgGaDGA==,type:str]
sops:
    age:
        - recipient: age17zqyk4za0q6md4tp0grlmlxnhppjvsnfalx987wsl8fgmhfx4fzq3g69m3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ3BESlFMdE1XZmpxbmNq
            RTcyYTNWTi80aFhRZUV1UHBDdzg3U1IydkNzCjlSU1VzNHFHUlNSNmsxMWlRMEY0
            RzMrN1NabVhCMWNrMUxmeHJRVm5XT3cKLS0tIDFGV1BtZVJsOEp0aUd6VUpwaGZl
            RGcrMHFmdHZrSWdBaFB2MlBYRGlOY1kKy/keZ8yVaOo3v7Cq1AgZlvQtI/Dsg59d
            +undI/IobtkFV8YURldyM8qnvxNWzyHwAJL0Pu66jrsgWG95ORybkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T22:52:22Z"
    mac: ENC[AES256_GCM,data:mNaXBkivFEOsggcEmG/dqN9NSJhKx+fGj1X8bcMOgqGTTCLoiKg2Bj+lYNspFVOxG28ZZfdbWB1nCWrZU7ffBtHjnoTwZKOPVkIuPMkMQh9HlFakIiSB6KSGjenLH2DUdz8WUVk77gaqugiM8kBlooVHNpa860+WUj55tR38mMA=,iv:Td+czZZEGBi1AA8cF1l2ePuBvwtxdl/gJeYm2YK3tLA=,tag:VQGXwUjiNVk94pQma6P1Vw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:yU4=,iv:SRfd0HGJ4JjRHg34LPI9WdLwrAFbGPKVOrQYqPK1DLw=,tag:MtX56kvjZnd8FUmdkuSNNg==,type:str]
kind: ENC[AES256_GCM,data:mmSRayT9,iv:B2gwq3a3j6IwEnddod0jXqDD9EDcRVyGF9Cfr7T4BSA=,tag:ued6dsnMRrs2eJx5vsatew==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XcInelKKAvpaPFMwzKlwUHQ=,iv:V89jUMOfCBJEpuy3M4ESwamkSTTdTVDYaHv07SNIhlk=,tag:NDplqREJq8nqBDpgl6W0SA==,type:str]
    namespace: ENC[AES256_GCM,data:I/EJ+w==,iv:gigOmxvKUHHVSRipRXMJ53BXLtC4Qys/uPo8LK8TTEg=,tag:LkvHQ0wYDL4Vbp+2BCXjcA==,type:str]
type: ENC[AES256_GCM,data:oXPkYSHx,iv:rREke10y6O4CdSkWEegWDfIlG6EsRjFMqSEMEvYkMQ4=,tag:YAdhDATEm8B0EhHkeVQgow==,type:str]
stringData:
    password: ENC[AES256_GCM,data:YfYSJrPP/7itrxvCKn0fo3KDcoCByJHb2m6Pf5PCbKs=,iv:ST4yMzgMvLogdY3dmo02A2whh9QveZZNuFLzRIq+tA4=,tag:F58RQFumDcSL1URLx73juQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:NfeqhMlThaUuK7aMDsHPjDooAv4m6u9i+Rh4Y1vN8aw=,iv:xTtkW+JF3VsSFEIEcXm/qLggK9kzgcEX+9X9Am7jw7I=,tag:fCxtoUo+O/YdC4GLhCcE6g==,type:str]
sops:
    age:
        - recipient: age17zqyk4za0q6md4tp0grlmlxnhppjvsnfalx987wsl8fgmhfx4fzq3g69m3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ3BESlFMdE1XZmpxbmNq
            RTcyYTNWTi80aFhRZUV1UHBDdzg3U1IydkNzCjlSU1VzNHFHUlNSNmsxMWlRMEY0
            RzMrN1NabVhCMWNrMUxmeHJRVm5XT3cKLS0tIDFGV1BtZVJsOEp0aUd6VUpwaGZl
            RGcrMHFmdHZrSWdBaFB2MlBYRGlOY1kKy/keZ8yVaOo3v7Cq1AgZlvQtI/Dsg59d
            +undI/IobtkFV8YURldyM8qnvxNWzyHwAJL0Pu66jrsgWG95ORybkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T22:52:22Z"
    mac: ENC[AES256_GCM,data:mNaXBkivFEOsggcEmG/dqN9NSJhKx+fGj1X8bcMOgqGTTCLoiKg2Bj+lYNspFVOxG28ZZfdbWB1nCWrZU7ffBtHjnoTwZKOPVkIuPMkMQh9HlFakIiSB6KSGjenLH2DUdz8WUVk77gaqugiM8kBlooVHNpa860+WUj55tR38mMA=,iv:Td+czZZEGBi1AA8cF1l2ePuBvwtxdl/gJeYm2YK3tLA=,tag:VQGXwUjiNVk94pQma6P1Vw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:ehE=,iv:opRd3uuNv1Eqcbd2m9q9PZoGfdGo7YpNTtB34o+G/2A=,tag:wBqzj7kM1CuHQl7sWUJ1IA==,type:str]
kind: ENC[AES256_GCM,data:a1qncqLn,iv:EK24cNE9C3Il3bVHP5Hi56PkqGv7q3bmQiWo+ipC4/U=,tag:Q1zTRh+/tHQEe1795QyPBA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Qi/z5GrjoQ89GbuJ82ZH,iv:VQA5vvv+PyMwPQ+L3chLUe56YUgJ4QVscNgJfs/qtw0=,tag:LNUQJcZStEJCHHgXe7umLQ==,type:str]
    namespace: ENC[AES256_GCM,data:rjxVNg==,iv:wQ0z1fE9/6qqr/cJyuQGSlhdLV8KfgAIwJKx/0rnYlE=,tag:YQn2HX5pVaqYu+ko3RJSlg==,type:str]
type: ENC[AES256_GCM,data:DA8TxoFA,iv:r9xwGx3VPqQSXSx61yeRK/97CBGMLp118JRZRSTUsQM=,tag:H9lpf2H+zoakK4CFN08Ibg==,type:str]
stringData:
    app-id: ENC[AES256_GCM,data:MgwfJeJxTw==,iv:38IUADBqj5I/U+29Pao5OLyaeReAAjItU7wquE9364g=,tag:ZxEyBtiwHsF4YLbv36OGkQ==,type:str]
    installation-id: ENC[AES256_GCM,data:8TOY2EgqGTxf,iv:HVeC+sR5eOXHjYnf8BMFxWMettdbz11emDitUS1TGnQ=,tag:Tk4kT9MEQxiRCVky7gTNqQ==,type:str]
    private-key.pem: ENC[AES256_GCM,data:/kZ10jlP3X7q+nn2vKBd4BhAZUm3On+hmzZkTCwLKOYbxOXlFBMJeP1qLUPduYv52uowhK8bkGPWuniOuAhfuuBdR8jTdm6zc5xldTDyZdKL+KezyB7CPj/leq6m+5o66+8M17oqbyXyDJ+fC5g3OiskVw/0nErfxcjpsXXvFiiLV3cJ92C/PIuantlCeIKD4i4Dqoct6+l1kYsVBq1pDoCC30ke0VrYJ1VhqnoimAzRjcX73Jna4whMhG/Ni88Au6yBrEjqaynSuxc6R7fEWuOLbKTal3PDoHNC2gK/S/TsPgRT3aRXJgUJoqSsSyfXRIMYHkuTU1uV5iIRhX8Na7dYrnT03DBV0KqI5zcmsfIMXb+uCAXpQAtQ+d14UGbYEeU9jR2mLQfhnNtZy0J23m0mytbbFDPRm//ESxc8T+xiObyh6+qqSjVRSbgj2WrksTsqK3XhjNq10AbBgi1FWXM/fAlw44iaHrNvsNW30ujrRPdHUwI7CnJTzPBZtZt+3dZQ9FEbYfcjeWhbWRkpIONc9SzEuZAFL2/YMYMMa7AbtEDjNPTiuClmtQ9KPEuCcfBIA+Ox785H29tUR7I9TSCZSvsdiTAJyGW9RuVMBI+3E/3h+fLwKWZyRX36xHZwqevfAwcRJdY25JAyIuUWI0lYd3DghnF5fQFfTsgDk+lUE0FhcPKhXi38pPLiYW3fc3uFeWP2+PuSQzeTSUlgbtdNvS6aEIdAe37wSRGYglPEoVklE6KcoSkYt64t0spBtuB1qbJZby9j0B4W35Qcrs+Jyy0Mrl2RE0JIQrdOcNGX9EsEpdCNgfqZcMzOX2FDeX0DjbVugF/5zAFyHNpbDwSbdCCYrS6ixMmQht1LCS6bv3vgBBYVOqgaVe0AofGUPkyarLRAJZUeg7vJUMt6tgtahG1IWDnvclVegasOrUM6CkfoOtfy6Rg+Ax4zBcn4t+CX0tPxiTUYj6AMDa7rbfNVtezdeHUbrw1tuyebtRii1SvbEPyDxsCFYNw4EecB85VYq680Kyq6NLl+hNKYaCy7Us3b05zCh0Lsf5ZcH/3mH6gOS7FlJNGkNRMuJ9QgzWAdVklfohRsMjFpVx8riVT6O0W3uMf9LfQZVjnR1dUjJC4EZuzlIR2iOmodFpkwYWhqkLZ/ewFFXUj6RUM/DacfnyTSbN0buxQA+K57aav5nA9e8XmL2DcvA7AAHloQew8/pwdj5jAkLyQep+Ykk7GFUcYD+6DR8nrszU47kV7J2kctZJZ+CK6dDVq2RUwrArwW7I/SoBlF/Jie9M6TSvRzD2CmofX/CRUR//WwB5KQsqU4jsiEMssPHdvLG9N+gZk/J5ATW6DmmvnLDHOoEs6+fTvIXM51QIA9QYxoFl2VDO/3/Hac3X3tauwN5tgGG5ZznM68ndx5hIp/LUsHmpYdXMZAM6+22N1lBn0bRp/VdLRAvy7063glYrDAsZgUBZ4DGHgv7LvhfwUI5o/zcf15X7OceklI6M65M57Qt6FCDaejRFba0LJ81N3aDhmSeEk6fEpdhRkvcCLfhmO7epSUMkGhngJH6p3Thx89+x2cGWRhfAbPQ567+SBQvAZ1eqnodI0S29UckUaMKVvNQAduJ4CBKO/zZZO2bAvTBn8QWmVJ0JWCP2MHY2sHdvf9S+v+Dvt3LL/NicPHtUU/umUfxbeI1XixhEr3P+hFKAQ6mFs/05Osx1I14G0rqpscYBaVm99URNerctWESMrpmHVaEwg7WTE89zblnNCVTzUUX73ngGWU/Fz3SfxkRDxNiLi0F25nN5YJvnVtNpH52bY8gA5gYoudGqUIM9r9iXuBcX64qFhXNe9GlEOYGgWVWbW5wrwBpg50iHgwEgjorMr0mxZ5PUzhBPT4ptW0i8xP2hwrGJAR5SzU04R/nYbv044a46eZXHCcM6xK3O/7baIIu71v4BfOi78kH9pi8NZJgNFTHbY8pxqGnQtiC8ERKWV2bCExxEiQVc/hNP8nhxVY8Ow9eCAC1OHnWpKCHAF/Z1Jajyf1bDK83I25Dx3k0QHPAp4/W+XhEpNdGAGIX7KI1aWjxi0xkK0tka64Pa2AvZIQ6WbjxczKmeFmqArn23vC7OWFcT9L9pSBWXEnVvqWTIohaThU1WBO0tiGcWjpATQqgfjPOabYF2/GYAVdbgEJ+hKLVhqLbO+PXqRNSybS/Cgx7qhelpG6uNn1bXO57za8RDVnkp1ygg==,iv:EJpj8p9k0IIfDWbgK0icpOuVYYKiBc/Ec67yqd/xTWw=,tag:tgCJRqpjFFYmaxDLnEGEbw==,type:str]
sops:
    age:
        - recipient: age17zqyk4za0q6md4tp0grlmlxnhppjvsnfalx987wsl8fgmhfx4fzq3g69m3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ3BESlFMdE1XZmpxbmNq
            RTcyYTNWTi80aFhRZUV1UHBDdzg3U1IydkNzCjlSU1VzNHFHUlNSNmsxMWlRMEY0
            RzMrN1NabVhCMWNrMUxmeHJRVm5XT3cKLS0tIDFGV1BtZVJsOEp0aUd6VUpwaGZl
            RGcrMHFmdHZrSWdBaFB2MlBYRGlOY1kKy/keZ8yVaOo3v7Cq1AgZlvQtI/Dsg59d
            +undI/IobtkFV8YURldyM8qnvxNWzyHwAJL0Pu66jrsgWG95ORybkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T22:52:22Z"
    mac: ENC[AES256_GCM,data:mNaXBkivFEOsggcEmG/dqN9NSJhKx+fGj1X8bcMOgqGTTCLoiKg2Bj+lYNspFVOxG28ZZfdbWB1nCWrZU7ffBtHjnoTwZKOPVkIuPMkMQh9HlFakIiSB6KSGjenLH2DUdz8WUVk77gaqugiM8kBlooVHNpa860+WUj55tR38mMA=,iv:Td+czZZEGBi1AA8cF1l2ePuBvwtxdl/gJeYm2YK3tLA=,tag:VQGXwUjiNVk94pQma6P1Vw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:Eho=,iv:V51vPbfkwdSgY96DPOM8CDV2gMzU73N58ywC2hDZqKY=,tag:69M3IiOExRpv7CKl3vdNqg==,type:str]
kind: ENC[AES256_GCM,data:oXKZGani,iv:ChngTIucy1widP+l7dXSl0gt+3UMDtsy28f7U5aRvfg=,tag:MSE6GIFMZy6dxkLZAb9O+A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:003TJAjkwc15vO75ysQ=,iv:3l/W9xfdyB44ASB3z2dYqLpHgT8M3R3Yo7AuTH2uk0o=,tag:NI1uDcdr1DI/t3o3kppmjw==,type:str]
    namespace: ENC[AES256_GCM,data:PlMdGw==,iv:+PAWTBQy8r97SBKMpM/Lne34DNam3gSpvZ8d9SJky2Y=,tag:AUFcdg+I11yrX3jQhJ9Wdw==,type:str]
type: ENC[AES256_GCM,data:v8Uy19QZ,iv:XUFB8yo5bG5RfQv3Gl8IN+vxyOB9+2/FYN0YMBWh6Ew=,tag:xZMXbxOlOnxH2u6QyqBfEw==,type:str]
stringData:
    token: ENC[AES256_GCM,data:s1klWvD/WpaC7DOgrFzC78b+oqTLHeXVPY2sVkaKoHBN46XuSiBlywhTZcQ=,iv:M4KM4gxKrzCiW6lc2ZgHISBdrFD7iJfdsxDyxyFVjpI=,tag:S9jLAO5e268FSElIYSrQTQ==,type:str]
sops:
    age:
        - recipient: age17zqyk4za0q6md4tp0grlmlxnhppjvsnfalx987wsl8fgmhfx4fzq3g69m3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXQ3BESlFMdE1XZmpxbmNq
            RTcyYTNWTi80aFhRZUV1UHBDdzg3U1IydkNzCjlSU1VzNHFHUlNSNmsxMWlRMEY0
            RzMrN1NabVhCMWNrMUxmeHJRVm5XT3cKLS0tIDFGV1BtZVJsOEp0aUd6VUpwaGZl
            RGcrMHFmdHZrSWdBaFB2MlBYRGlOY1kKy/keZ8yVaOo3v7Cq1AgZlvQtI/Dsg59d
            +undI/IobtkFV8YURldyM8qnvxNWzyHwAJL0Pu66jrsgWG95ORybkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T22:52:22Z"
    mac: ENC[AES256_GCM,data:mNaXBkivFEOsggcEmG/dqN9NSJhKx+fGj1X8bcMOgqGTTCLoiKg2Bj+lYNspFVOxG28ZZfdbWB1nCWrZU7ffBtHjnoTwZKOPVkIuPMkMQh9HlFakIiSB6KSGjenLH2DUdz8WUVk77gaqugiM8kBlooVHNpa860+WUj55tR38mMA=,iv:Td+czZZEGBi1AA8cF1l2ePuBvwtxdl/gJeYm2YK3tLA=,tag:VQGXwUjiNVk94pQma6P1Vw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
